export const SAVE_USER_NAME = 'SAVE_USER_NAME';
export const SAVE_CHARACTER = 'SAVE_CHARACTER';
export const SAVE_CHARACTER_NAME = 'SAVE_CHARACTER_NAME';
export const SAVE_ICE_BREAKER_INFORMATION = 'SAVE_ICE_BREAKER_INFORMATION';
