export const STAGES = {
  ASK_FOR_USER_NAME: 'ASK_FOR_USER_NAME',
  CHARACTER_SELECTION: 'CHARACTER_SELECTION',
  PROLOGUE: 'PROLOGUE',
  TRAVELER_STORYLINE: 'TRAVELER_STORYLINE',
  MEET_THE_MENTOR: 'MEET_THE_MENTOR',
  MENTOR_INTRODUCTION: 'MENTOR_INTRODUCTION',
  ASK_FOR_CHARACTER_NAME: 'ASK_FOR_CHARACTER_NAME',
}
