export const STAGES = {
  ASK_FOR_USER_NAME: 'ASK_FOR_USER_NAME',
  CHARACTER_SELECTION: 'CHARACTER_SELECTION',
  PROLOGUE: 'PROLOGUE',
  TRAVELER_STORYLINE: 'TRAVELER_STORYLINE',
  MEET_THE_MENTOR: 'MEET_THE_MENTOR',
  MENTOR_INTRODUCTION: 'MENTOR_INTRODUCTION',
  MENTOR_FAREWELL: 'MENTOR_FAREWELL',
  OPEN_THE_DOOR: 'OPEN_THE_DOOR',
  EARTHQUAKE: 'EARTHQUAKE',
  GLITCH: 'GLITCH',
}
